import { IPO } from "./db/schema";

export const sampleIPOs: Partial<IPO>[] = [
  // ==========================================
  // INDIA - Existing IPOs
  // ==========================================
  {
    id: "1",
    name: "Hexaware Technologies",
    slug: "hexaware-technologies",
    market: "india",
    exchange: "NSE/BSE",
    status: "listed",
    priceMin: "674",
    priceMax: "708",
    listingPrice: "745",
    lotSize: 21,
    issueSize: "8,750 Cr",
    openDate: new Date("2025-02-12"),
    closeDate: new Date("2025-02-14"),
    allotmentDate: new Date("2025-02-17"),
    listingDate: new Date("2025-02-19"),
    description: "Leading IT services company providing digital transformation solutions globally.",
    sector: "Information Technology",
  },
  {
    id: "2",
    name: "Dr. Agarwals Health Care",
    slug: "dr-agarwals-health-care",
    market: "india",
    exchange: "NSE/BSE",
    status: "listed",
    priceMin: "382",
    priceMax: "402",
    listingPrice: "402",
    lotSize: 37,
    issueSize: "3,027 Cr",
    openDate: new Date("2025-01-29"),
    closeDate: new Date("2025-01-31"),
    allotmentDate: new Date("2025-02-03"),
    listingDate: new Date("2025-02-04"),
    description: "One of India's largest eye care networks with 100+ hospitals.",
    sector: "Healthcare",
  },
  {
    id: "3",
    name: "Quality Power Electrical",
    slug: "quality-power-electrical",
    market: "india",
    exchange: "NSE/BSE",
    status: "listed",
    priceMin: "401",
    priceMax: "425",
    listingPrice: "430",
    lotSize: 35,
    issueSize: "858 Cr",
    openDate: new Date("2025-02-14"),
    closeDate: new Date("2025-02-18"),
    allotmentDate: new Date("2025-02-19"),
    listingDate: new Date("2025-02-24"),
    description: "Manufacturer of power transformers and electrical equipment.",
    sector: "Energy & Power",
  },
  {
    id: "5",
    name: "Ventive Hospitality",
    slug: "ventive-hospitality",
    market: "india",
    exchange: "NSE/BSE",
    status: "listed",
    priceMin: "610",
    priceMax: "643",
    listingPrice: "716",
    lotSize: 23,
    issueSize: "1,600 Cr",
    openDate: new Date("2024-12-20"),
    closeDate: new Date("2024-12-24"),
    allotmentDate: new Date("2024-12-26"),
    listingDate: new Date("2024-12-30"),
    description: "Luxury hospitality company operating premium hotel brands.",
    sector: "Hospitality",
  },

  // ==========================================
  // INDIA - New Real IPOs (2024-2025)
  // ==========================================
  {
    id: "11",
    name: "Bajaj Housing Finance",
    slug: "bajaj-housing-finance",
    market: "india",
    exchange: "NSE/BSE",
    status: "listed",
    priceMin: "66",
    priceMax: "70",
    listingPrice: "150",
    lotSize: 214,
    issueSize: "6,560 Cr",
    openDate: new Date("2024-09-09"),
    closeDate: new Date("2024-09-11"),
    allotmentDate: new Date("2024-09-12"),
    listingDate: new Date("2024-09-16"),
    description: "Subsidiary of Bajaj Finance, one of India's largest housing finance companies offering home loans, loans against property, and developer financing.",
    sector: "Financial Services",
  },
  {
    id: "12",
    name: "Ola Electric",
    slug: "ola-electric",
    market: "india",
    exchange: "NSE/BSE",
    status: "listed",
    priceMin: "72",
    priceMax: "76",
    listingPrice: "76",
    lotSize: 197,
    issueSize: "6,146 Cr",
    openDate: new Date("2024-08-02"),
    closeDate: new Date("2024-08-06"),
    allotmentDate: new Date("2024-08-07"),
    listingDate: new Date("2024-08-09"),
    description: "India's leading electric two-wheeler manufacturer, part of the Ola group. Operates the world's largest e-scooter factory.",
    sector: "Electric Vehicles",
  },
  {
    id: "13",
    name: "FirstCry (Brainbees Solutions)",
    slug: "firstcry-brainbees-solutions",
    market: "india",
    exchange: "NSE/BSE",
    status: "listed",
    priceMin: "440",
    priceMax: "465",
    listingPrice: "651",
    lotSize: 32,
    issueSize: "4,194 Cr",
    openDate: new Date("2024-08-06"),
    closeDate: new Date("2024-08-08"),
    allotmentDate: new Date("2024-08-09"),
    listingDate: new Date("2024-08-13"),
    description: "Asia's largest multi-brand platform for mothers, babies, and kids, operating online and offline retail stores.",
    sector: "E-Commerce / Retail",
  },
  {
    id: "14",
    name: "Swiggy",
    slug: "swiggy",
    market: "india",
    exchange: "NSE/BSE",
    status: "listed",
    priceMin: "371",
    priceMax: "390",
    listingPrice: "420",
    lotSize: 38,
    issueSize: "11,327 Cr",
    openDate: new Date("2024-11-06"),
    closeDate: new Date("2024-11-08"),
    allotmentDate: new Date("2024-11-11"),
    listingDate: new Date("2024-11-13"),
    description: "Leading food delivery and quick commerce platform in India, competing with Zomato. Also operates Instamart for instant grocery delivery.",
    sector: "Food Tech / E-Commerce",
  },
  {
    id: "15",
    name: "NTPC Green Energy",
    slug: "ntpc-green-energy",
    market: "india",
    exchange: "NSE/BSE",
    status: "listed",
    priceMin: "102",
    priceMax: "108",
    listingPrice: "111",
    lotSize: 138,
    issueSize: "10,000 Cr",
    openDate: new Date("2024-11-19"),
    closeDate: new Date("2024-11-22"),
    allotmentDate: new Date("2024-11-25"),
    listingDate: new Date("2024-11-27"),
    description: "Renewable energy subsidiary of NTPC Limited, India's largest power generation company. Focuses on solar and wind energy projects.",
    sector: "Renewable Energy",
  },
  {
    id: "16",
    name: "Afcons Infrastructure",
    slug: "afcons-infrastructure",
    market: "india",
    exchange: "NSE/BSE",
    status: "listed",
    priceMin: "440",
    priceMax: "463",
    listingPrice: "424",
    lotSize: 32,
    issueSize: "5,430 Cr",
    openDate: new Date("2024-10-25"),
    closeDate: new Date("2024-10-29"),
    allotmentDate: new Date("2024-10-30"),
    listingDate: new Date("2024-11-04"),
    description: "Shapoorji Pallonji group company, one of India's leading infrastructure engineering and construction firms specializing in marine, oil & gas, and urban infrastructure.",
    sector: "Infrastructure",
  },
  {
    id: "17",
    name: "Hyundai Motor India",
    slug: "hyundai-motor-india",
    market: "india",
    exchange: "NSE/BSE",
    status: "listed",
    priceMin: "1865",
    priceMax: "1960",
    listingPrice: "1934",
    lotSize: 7,
    issueSize: "27,870 Cr",
    openDate: new Date("2024-10-15"),
    closeDate: new Date("2024-10-17"),
    allotmentDate: new Date("2024-10-18"),
    listingDate: new Date("2024-10-22"),
    description: "India's second-largest car manufacturer and a subsidiary of Hyundai Motor Company, South Korea. The largest IPO in Indian history.",
    sector: "Automobile",
  },
  {
    id: "18",
    name: "Waaree Energies",
    slug: "waaree-energies",
    market: "india",
    exchange: "NSE/BSE",
    status: "listed",
    priceMin: "1427",
    priceMax: "1503",
    listingPrice: "2500",
    lotSize: 9,
    issueSize: "4,321 Cr",
    openDate: new Date("2024-10-21"),
    closeDate: new Date("2024-10-23"),
    allotmentDate: new Date("2024-10-24"),
    listingDate: new Date("2024-10-28"),
    description: "India's largest solar PV module manufacturer with 12 GW capacity. Major exporter of solar modules globally.",
    sector: "Solar Energy",
  },
  {
    id: "19",
    name: "Sagility India",
    slug: "sagility-india",
    market: "india",
    exchange: "NSE/BSE",
    status: "listed",
    priceMin: "28",
    priceMax: "30",
    listingPrice: "31",
    lotSize: 500,
    issueSize: "2,107 Cr",
    openDate: new Date("2024-11-05"),
    closeDate: new Date("2024-11-07"),
    allotmentDate: new Date("2024-11-08"),
    listingDate: new Date("2024-11-12"),
    description: "Technology-enabled healthcare services company providing solutions to US health insurance payers, providers, and pharma companies.",
    sector: "Healthcare IT",
  },
  {
    id: "20",
    name: "Niva Bupa Health Insurance",
    slug: "niva-bupa-health-insurance",
    market: "india",
    exchange: "NSE/BSE",
    status: "listed",
    priceMin: "70",
    priceMax: "74",
    listingPrice: "78",
    lotSize: 200,
    issueSize: "2,200 Cr",
    openDate: new Date("2024-11-07"),
    closeDate: new Date("2024-11-11"),
    allotmentDate: new Date("2024-11-12"),
    listingDate: new Date("2024-11-14"),
    description: "Joint venture between Fettle Tone LLP (Bupa Group) and True North. One of India's leading standalone health insurance companies.",
    sector: "Insurance",
  },

  // ==========================================
  // US Market - Sample IPOs
  // ==========================================
  {
    id: "6",
    name: "CoreWeave",
    slug: "coreweave",
    market: "us",
    exchange: "NASDAQ",
    status: "listed",
    priceMin: "47",
    priceMax: "55",
    listingPrice: "40",
    issueSize: "$1.5B",
    openDate: new Date("2025-03-27"),
    listingDate: new Date("2025-03-28"),
    description: "AI-focused cloud computing infrastructure provider backed by NVIDIA. Priced below expected range at $40/share.",
    sector: "Cloud Computing / AI",
  },
  {
    id: "7",
    name: "Klarna",
    slug: "klarna",
    market: "us",
    exchange: "NYSE",
    status: "listed",
    priceMin: "35",
    priceMax: "37",
    listingPrice: "52",
    issueSize: "$1.37B",
    openDate: new Date("2025-09-10"),
    listingDate: new Date("2025-09-10"),
    description: "Leading Buy Now, Pay Later fintech platform from Sweden. IPO priced at $40, opened at $52.",
    sector: "Fintech",
  },
  {
    id: "8",
    name: "Cerebras Systems",
    slug: "cerebras-systems",
    market: "us",
    exchange: "NASDAQ",
    status: "upcoming",
    priceMin: "28",
    priceMax: "34",
    issueSize: "$600M",
    openDate: new Date("2026-04-15"),
    description: "AI chip maker competing with NVIDIA, building the world's largest AI processors. IPO delayed due to CFIUS review, now targeting Q2 2026.",
    sector: "Semiconductors / AI",
  },
  {
    id: "10",
    name: "Reddit",
    slug: "reddit",
    market: "us",
    exchange: "NYSE",
    status: "listed",
    priceMin: "31",
    priceMax: "34",
    listingPrice: "47",
    issueSize: "$748M",
    openDate: new Date("2024-03-19"),
    listingDate: new Date("2024-03-21"),
    description: "Social news and discussion platform with communities on every topic.",
    sector: "Social Media / Technology",
  },
];

export function getIPOsByMarket(market: "india" | "us") {
  return sampleIPOs.filter((ipo) => ipo.market === market);
}

export function getIPOsByStatus(market: "india" | "us", status: "upcoming" | "open" | "listed") {
  return sampleIPOs.filter((ipo) => ipo.market === market && ipo.status === status);
}

export function getIPOBySlug(market: string, slug: string) {
  return sampleIPOs.find((ipo) => ipo.market === market && ipo.slug === slug);
}

export function getFeaturedIPOs() {
  // Return a mix of interesting IPOs: upcoming, open, and notable recently listed ones
  const upcoming = sampleIPOs.filter((ipo) => ipo.status === "upcoming");
  const open = sampleIPOs.filter((ipo) => ipo.status === "open");
  const notableListed = sampleIPOs
    .filter((ipo) => ipo.status === "listed")
    .sort((a, b) => {
      // Sort by listing date descending, most recent first
      const dateA = a.listingDate ? new Date(a.listingDate).getTime() : 0;
      const dateB = b.listingDate ? new Date(b.listingDate).getTime() : 0;
      return dateB - dateA;
    })
    .slice(0, 2);

  const featured = [...upcoming.slice(0, 2), ...open.slice(0, 1), ...notableListed];
  return featured.slice(0, 4);
}
